### ISSUE TITLE
Code in git does not match what is available for install via PyPi

### ISSUE THREAD

**Issue by mlasevich** [kostko/dsc-it100#2]
If installed via PyPi/pip, you get same version number (0.1.1) as in git, but different API (driver constructor) - as a result, example code does not work against pip installed code (example has baudrate parameter not available in code). Please bump version to avoid confusion.

Thanks

-M

**Comment by kostko** [comment]
Thanks, fixed.

**Comment by mlasevich** [comment]
Not sure how long it usually takes or if you need to do anything, but FYI - the version on PyPi is still 0.1.1

https://pypi.python.org/pypi/dsc-it100

**Comment by kostko** [comment]
Should be up now.
