### ISSUE TITLE
Project should have a license

### ISSUE THREAD

**Issue by llunved** [kostko/dsc-it100#3]
This project does not seem to have a license right now. It would be good if you could add one so users get clarity. I'd recommend GPLv3

**Comment by kostko** [comment]
In `setup.py` I list:
```python
    'License :: OSI Approved :: GNU Affero General Public License v3',
```

I can also add a separate LICENSE file if that is something that should be done.

**Comment by llunved** [comment]
Ahh. Sorry, I had missed that. 
AGPL v3 is a great license. 

Based on the recommendations by the GNU project I think an explicit license file and a license header in each file would be good: http://www.gnu.org/licenses/gpl-howto.html

Thanks for doing the dsc work!

Cheers.
